import {initializeApp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyCS82yUDIe3f0u_FAppo2j4tHEaOiTdj0M",authDomain:"books-cdb85.firebaseapp.com",projectId:"books-cdb85",storageBucket:"books-cdb85.firebasestorage.app",messagingSenderId:"329453613073",appId:"1:329453613073:web:3aef47b2f047f63eac81b0",measurementId:"G-07VG2B49H7"};
const auth=getAuth(initializeApp(firebaseConfig)),db=getFirestore(); const stateRef=doc(db,"gymnasium","orders");
let state={units:[]},activeId="",subject="Все предметы",search="",saveTimer,type="class";
const $=s=>document.querySelector(s), money=n=>`${n.toFixed(2).replace(".",",")} руб.`, total=u=>u.lines.reduce((s,l)=>s+l.price*l.quantity,0), active=()=>state.units.find(u=>u.id===activeId);

$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";try{await signInWithEmailAndPassword(auth,$("#email").value,$("#password").value)}catch{$("#loginError").textContent="Неверный адрес или пароль"}};
$("#logout").onclick=()=>signOut(auth); onAuthStateChanged(auth,async user=>{const ok=user?.email==="lukshaolga1982@gmail.com";$("#login").hidden=ok;$("#app").hidden=!ok;if(!ok)return;const snap=await getDoc(stateRef);state=snap.exists()?snap.data():{units:[]};activeId=state.units[0]?.id||"";render();$("#saveStatus").textContent="Все изменения сохранены"});
function save(){clearTimeout(saveTimer);$("#saveStatus").textContent="Сохраняю…";saveTimer=setTimeout(async()=>{try{await setDoc(stateRef,state);$("#saveStatus").textContent="Все изменения сохранены"}catch{$("#saveStatus").textContent="Ошибка сохранения"}},450)}
function change(patch){state.units=state.units.map(u=>u.id===activeId?{...u,...patch}:u);render();save()}
function render(){const a=active();$("#summary").innerHTML=`<div><span>Классов и групп</span><b>${state.units.length}</b></div><div><span>Всего учащихся</span><b>${state.units.reduce((s,u)=>s+u.students,0)}</b></div><div class="sum"><span>Общая сумма</span><b>${money(state.units.reduce((s,u)=>s+total(u),0))}</b></div><button onclick="print()">Распечатать</button>`;$("#units").innerHTML=state.units.map(u=>`<button class="unit ${u.id===activeId?"active":""}" data-id="${u.id}"><i>${u.grade}</i><span><b>${u.name}</b><small>${u.type==="group"?"Группа":"Класс"} · ${u.students} чел.</small></span><em>${money(total(u))}</em></button>`).join("");document.querySelectorAll(".unit").forEach(b=>b.onclick=()=>{activeId=b.dataset.id;subject="Все предметы";render()});if(!a){$("#content").innerHTML=`<div class="empty"><h2>Добавьте первый класс</h2><p>Затем выберите необходимые пособия.</p><button id="emptyAdd">Добавить список</button></div>`;$("#emptyAdd").onclick=openDialog;return}const items=CATALOG.filter(i=>i.grade===a.grade),subjects=["Все предметы",...new Set(items.map(i=>i.subject))],shown=items.filter(i=>(subject==="Все предметы"||i.subject===subject)&&`${i.title} ${i.code}`.toLowerCase().includes(search.toLowerCase()));$("#content").innerHTML=`<div class="unitHead"><div><small>${a.type==="group"?"Учебная группа":a.grade+" класс"}</small><input id="activeName" value="${esc(a.name)}"></div><label>Учащихся<input id="activeStudents" type="number" min="0" value="${a.students}"></label><button id="deleteUnit">Удалить</button></div><div class="cards"><div><span>На одного ученика</span><b>${money(a.students?total(a)/a.students:0)}</b></div><div><span>Заказ для ${esc(a.name)}</span><b>${money(total(a))}</b></div></div><div class="catalogHead"><div><h2>Пособия для ${a.grade} класса</h2><p>Прайс на 7 августа 2026 года</p></div><input id="search" placeholder="Поиск…" value="${esc(search)}"></div><div class="tabs">${subjects.map(s=>`<button data-subject="${esc(s)}" class="${s===subject?"active":""}">${s}</button>`).join("")}</div><div class="books">${shown.map(i=>book(i,a)).join("")}</div>`;bind(a)}
function book(i,a){const l=a.lines.find(x=>x.itemId===i.id);return `<article class="${l?"selected":""}"><button class="check" data-toggle="${i.id}">${l?"✓":""}</button><div class="bookName"><small>${i.subject} · ${i.code}</small><b>${i.title}</b></div><label>Цена<input data-price="${i.id}" type="number" step="0.01" ${l?"":"disabled"} value="${l?.price??i.price}"></label><label>Заказывают<input data-qty="${i.id}" type="number" min="0" max="${a.students}" ${l?"":"disabled"} value="${l?.quantity??0}"></label><div><small>Сумма</small><b>${money(l?l.price*l.quantity:0)}</b></div></article>`}
function bind(a){$("#activeName").onchange=e=>change({name:e.target.value});$("#activeStudents").onchange=e=>change({students:Math.max(0,+e.target.value)});$("#deleteUnit").onclick=()=>{if(confirm(`Удалить «${a.name}»?`)){state.units=state.units.filter(u=>u.id!==a.id);activeId=state.units[0]?.id||"";render();save()}};$("#search").oninput=e=>{search=e.target.value;render()};document.querySelectorAll("[data-subject]").forEach(b=>b.onclick=()=>{subject=b.dataset.subject;render()});document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>{const i=CATALOG.find(x=>x.id===b.dataset.toggle),has=a.lines.some(l=>l.itemId===i.id);change({lines:has?a.lines.filter(l=>l.itemId!==i.id):[...a.lines,{itemId:i.id,quantity:a.students,price:i.price}]})});document.querySelectorAll("[data-price]").forEach(x=>x.onchange=()=>line(x.dataset.price,{price:+x.value}));document.querySelectorAll("[data-qty]").forEach(x=>x.onchange=()=>line(x.dataset.qty,{quantity:Math.min(a.students,Math.max(0,+x.value))}))}
function line(id,patch){const a=active();change({lines:a.lines.map(l=>l.itemId===id?{...l,...patch}:l)})}function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function openDialog(){$("#unitDialog").showModal()}$("#addUnit").onclick=openDialog;$("#addUnitBottom").onclick=openDialog;[5,6,7,8,9,10,11].forEach(g=>$("#unitGrade").add(new Option(g,g)));document.querySelectorAll("[data-type]").forEach(b=>b.onclick=()=>{type=b.dataset.type;document.querySelectorAll("[data-type]").forEach(x=>x.classList.toggle("active",x===b))});$("#unitForm").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const name=$("#unitName").value.trim();if(!name)return;const u={id:crypto.randomUUID(),name,grade:+$("#unitGrade").value,students:+$("#unitStudents").value,type,lines:[]};state.units.push(u);activeId=u.id;$("#unitName").value="";$("#unitDialog").close();render();save()};
